### ISSUE TITLE
[Solution]: Functions and Fractals - Recursive Trees - Bash!

### ISSUE THREAD

**Issue by sounishnath003** [Thomas-George-T/HackerRank-The-Linux-Shell-Challenges-Solutions#3]
Hello! ✌

I started learning Shell Scripting and started practicing at Hackerrank and while practicing questions I stuck at [Functions and Fractals](https://www.hackerrank.com/challenges/fractal-trees-all/problem) question and google search to get the idea of solution I found your repo as my first result! 

As a beginner who started learning Shell scripting, I found your this repository very helpful, each command I first learning from youtube & when stuck I reach out to this repository.

The mentioned question does not have a solution, nor I could solve it, I found an answer, and want to contribute to this repository with the solution I got.

```bash
declare -A a

# credits to https://github.com/MaskRay/HackerRank/blob/master/shell/fractal-trees-all.sh
# d - depth
# l = length
# r = row
# c = column

f() {
    local d=$1 l=$2 r=$3 c=$4
    [[ $d -eq 0 ]] && return
    for ((i=l; i; i--)); do
        a[$((r-i)).$c]=1
    done
    ((r -= l))
    for ((i=l; i; i--)); do
        a[$((r-i)).$((c-i))]=1
        a[$((r-i)).$((c+i))]=1
    done
    f $((d-1)) $((l/2)) $((r-l)) $((c-l))
    f $((d-1)) $((l/2)) $((r-l)) $((c+l))
}
read n
f $n 16 63 49
for ((i=0; i<63; i++)); do
    for ((j=0; j<100; j++)); do
        if [[ ${a[$i.$j]} ]]; then
            printf 1
        else
            printf _
        fi
    done
    echo
done
```

I hope this adds a complete mark to your repository and it will eventually help people in the community!

**Comment by Thomas-George-T** [comment]
Hey @sounishnath003 

I am happy that you find my work helpful. I didn't post the solution for this question since I refused to acknowledge this as a learning challenge. I had hoped that eventually that I would change my mind and get around to it.

About your solution, please feel free to raise a pull request with the solution that you found. I will review the request and merge it accordingly.

Happy learning!

**Comment by sounishnath003** [comment]
First of all, Thank you very much and indeed this helps me a lot knowing how to write a shell script, and without knowing the inbuilt Linux commands it adds no meaning to it!.

Need to learn a lot from you!
Thanks, Sir!

**Comment by Thomas-George-T** [comment]
Merged your PR. Closing this issue. Cheers :)
