### ISSUE TITLE
About 'Sed' command #1.sh Solution 

### ISSUE THREAD

**Issue by imostafizur** [Thomas-George-T/HackerRank-The-Linux-Shell-Challenges-Solutions#7]
Your solution: $ sed -e 's/the /this /1'
It showing error.
After then i done this like this  sed -e 's/\<the\>/this/'

**Comment by Thomas-George-T** [comment]
Hey, Thanks for bringing this up. 

I resubmitted my 3 year old solution right now and it worked like a charm. Please see below:

<img width="876" alt="image" src="https://user-images.githubusercontent.com/20851812/188228795-ce07d07f-4986-4e4b-bef0-c74710698670.png">

<img width="919" alt="image" src="https://user-images.githubusercontent.com/20851812/188228889-024a76b5-575d-48e9-b5e7-2eb6fbd9169c.png">

I guess these things keep happening from time to time.

**Comment by Thomas-George-T** [comment]
If it happens again, I can change it. Thanks for letting me know.
